### ISSUE TITLE
L04-22 - Fragen/Themen Sammlung

### ISSUE THREAD

**Issue by Plagiatus** [hs-furtwangen/GIS-SoSe-2020#1]
Sind Fragen während der Bearbeitung von L00 aufgekommen? Ist noch irgendetwas unklar? Sammeln Sie hier schonmal Ihre Fragen damit diese sicher im Q&A Termin angesprochen werden.

**Comment by Nesli13** [comment]
Hallo, ich habe aus versehen mein repositorie gelöscht und ein neues erstellt. Wie kann ich mich jetzt nochmal registrieren? Das geht nicht, weil ich schon registriert bin.
