### ISSUE TITLE
A9 Probleme mit dem query String

### ISSUE THREAD

**Issue by sarahmohring** [hs-furtwangen/GIS-SoSe-2020#10]
Hallo, 
mein Code schafft es nicht, den URL mit den Form-Eingaben richtig formatiert auszugeben (statt key-Werte-Paaren wird nur der URL ausgegeben), und bei der JSON-Ausgabe kommt in der Konsole immer der Fehler "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"

Was mache ich falsch?

LG Sarah

**Comment by Plagiatus** [comment]
Entschuldige, habe ich hier nicht so schnell gesehen.

Frage wurde auf Discord beantwortet (https://discordapp.com/channels/701467403212816394/701470148846026812/725995970072018986), es lag zum einen daran, dass der Server nicht den neuen Code verwendet hat, zum anderen daran, dass im verwendeten URL zwei // vorhanden waren.
