### ISSUE TITLE
Die Links in meinem Steckbrief werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by ChristianHauser** [hs-furtwangen/GIS-SoSe-2020#4]
Da gibts bestimmt eine einfache Lösung zu aber ich komm grad einfach nicht drauf.
Dass hier ist der Link zu meinem Steckbrief zumindest sollte er es sein hoffe sie können mir helfen: https://christianhauser.github.io/gis_SoSe2020/Steckbrief/

**Comment by Plagiatus** [comment]
index.html?

**Comment by nikxwar** [comment]
Du hast die Datei in index.html umbenannt, sie muss aber steckbrief.htm heißen.

**Comment by ChristianHauser** [comment]
Dankeschön hab echt viel zu lange danach gesucht.. Lg

Niklas Krieg <notifications@github.com> schrieb am Sa., 9. Mai 2020, 00:24:

**Comment by Plagiatus** [comment]
bitte das Issue schließen wenn es erledigt ist.
