### ISSUE TITLE
Das Pushen dauert zu lange

### ISSUE THREAD

**Issue by daj00** [hs-furtwangen/GIS-SoSe-2020#5]
Hallo, 

Ich habe die Aufgaben fertig nur das Pushen bzw. hochladen dauert ewig. Das Video hat 41MB und sollte eigentlich kein Problem sein. Ich bin nun eine Stunde drüber und weil meine Aufgabe seit 2 Stunden hochlädt. 

Kann mir jemand helfen? 

Liebe Grüße
David Katalenic (MIB2)

**Comment by Plagiatus** [comment]
41MB ist ein Problem für git, da git selbst eine Dateigrößenbeschränkung von 25MB hat. Hier Infos dazu wie man das erweitern kann wenn es denn unbedingt sein muss: https://git-lfs.github.com/

> Ich bin nun eine Stunde drüber

über was? Abgabe ist erst morgen um 18 Uhr, nicht heute.

**Comment by Plagiatus** [comment]
Hat sich das Problem nun gelöst? Oder haste du eine andere Lösung gefunden? Wenn das Problem nicht mehr relevant ist, bitte issue schließen.
