### ISSUE TITLE
Zu wenig Tags?

### ISSUE THREAD

**Issue by alinakle** [hs-furtwangen/GIS-SoSe-2020#6]
Anscheinend hat jeder von uns zu wenig Tags benutzt. So wie ich die Aufgabe verstanden hatte mussten wir 12 verschiedene Tags benutzen, deshalb versteh ich nicht genau was das Problem ist. Waren 12 Tags auf jeder einzelnen Seite gemeint? Oder zählen die Tags auf der Used_Tags-Seite nicht? Falls ja hätte das in der Aufgabe vielleicht besser definiert werden müssen, den der Großteil hat es "falsch" und ich bin mir ziemlich sicher das der Großteil dachte er hat es richtig. Wieso sollten alle es mit Absicht falsch machen?
Wie man in Tim Knopps Feedback sehen kann hat wohl nicht mal Andreas Reich die Aufgabe richtig verstanden, so wie wir alle nicht. Finde ich nicht gut das wir wegen einer mangelhaft definierten Aufgabe alle eine Ampel bekommen. Bitte um eine Rückmeldung.

**Comment by alinakle** [comment]
Wie man in Tim Knopps Feedback sehen kann hat wohl nicht mal Andreas Reich die Aufgabe richtig verstanden, so wie wir alle nicht. Finde ich nicht gut das wir wegen einer mangelhaft definierten Aufgabe alle eine Ampel bekommen.

**Comment by Plagiatus** [comment]
um die Aufgabe zu zitieren:
> Verwenden Sie für die 3 HTML Seiten jeweils die grundlegende HTML5 Seitenstruktur und zusätzlich zu den gundlegenden Elementen mindestens 12 verschiedene HTML5 Elemente

Ich kann Ihre Verwirrung ein wenig nachvollziehen, aber in der Aufgabe steht ohne die Füllwörter:

> Verwenden Sie für die 3 HTML Seiten jeweils die Grundlagenstruktur und zusätzlich mindestens 12 Elemente

Also JEWEILS die Grundlagen und 12 verschiedene Elemente auf den drei geforderten Seiten. Außerdem die Tabelle mit den verwendeten Tags.  
Die Aufgabe ist meiner Meinung nach also klar definiert, wenn man sie sich richtig durchliest. Das gibt auch Andreas Reich zu wenn er sagt "ich habe die Aufgabe falsch gelesen". er sagt "falsch gelesen", nicht "falsch verstanden".

Wir nehmen Ihr Feedback aber gerne auf und werden versuchen, die kommenden Aufgaben noch eindeutiger zu definieren. Bitte nutzen Sie die Praktikas oder die Issues um Unklarheiten oder Interpretationsspielräume klar zu stellen.

**Comment by alinakle** [comment]
Dann sind wir wohl anderer Meinung :) Freut mich aber das die Kritik angenommen wird.
