### ISSUE TITLE
Aufgabe 2 nicht verbessert? 

### ISSUE THREAD

**Issue by daj00** [hs-furtwangen/GIS-SoSe-2020#7]
Hi,

ich habe doch die Aufgabe 2 verbessert und wenn nicht, was fehlt denn noch? 

LG David Katalenic

**Comment by Logophoman** [comment]
Also das hier sind jeweils die Anzahl der Tags die auf den 3 Seiten verwendet wurden:

![image](https://user-images.githubusercontent.com/28789967/82217355-94086900-991a-11ea-8f43-dee6c1a98434.png)
---
![image](https://user-images.githubusercontent.com/28789967/82217437-b1d5ce00-991a-11ea-97e0-00e3e69aeacc.png)
---
![image](https://user-images.githubusercontent.com/28789967/82217502-cca84280-991a-11ea-9048-71c2e77cac09.png)

Und das hier sind die W3 Errors der 3 Seiten:

![image](https://user-images.githubusercontent.com/28789967/82217555-e053a900-991a-11ea-8640-12e54ddc2e13.png)
---
![image](https://user-images.githubusercontent.com/28789967/82217613-f5303c80-991a-11ea-8e6a-7876d0660f18.png)
---
![image](https://user-images.githubusercontent.com/28789967/82217826-450f0380-991b-11ea-9640-f3ba0425b3f4.png)

Kann es sein, dass du vielleicht deine Verbesserungen nicht hochgeladen hast? 🤔

**Comment by Logophoman** [comment]
Gefehlt hätten insgesamt 12 Tags (Sodass es dann je 12 Tags pro Seite gewesen wären). W3 Errors hätte es keine geben dürfen.

**Comment by daj00** [comment]
Also ich habe es jetzt nochmal neu hochgeladen und hoffe das passt jetzt so. Ich bin grade dabei die CSS-Aufgabe (3) zu machen und die Aufgabe 4 wird diese Woche pünktlich kommen. 

Ich verstehe immernoch nicht was die W3-Errors bedeuten aber ich habe nun meine src-Elemente anders deklariert und die Größen bearbeitet. Sollten es immernoch zu wenig Tags sein korrigiere ich dies erneut. 

Danke für die Rückmeldung.

**Comment by Logophoman** [comment]
Also Aufgabe 02 brauchst du nicht zu verbessern, die ist schon durch. Du kannst aber Aufgabe 3 Verbessern (das ist die Aufgabe mit dem CSS). Du solltest deine Aufgaben mit dem W3 Validierer auf Errors testen - der zeigt dir dann immer an was noch falsch ist:
[Validierer](https://validator.w3.org)

**Comment by Plagiatus** [comment]
Und ich habe mir deine Aufgaben gerade nochmal angeschaut:
Da sind immernoch einige Fehler vom Validierer drin, außerdem sind es immernoch keine 12 verschiedene (und valide) HTML5 Tags pro Seite.

Und wie @Logophoman schon sagt: Aufgabe 2 ist durch, da gibt es auch keine Ampeln mehr zurück.

Wenn du die Fehlermeldungen vom Validierer nicht verstehst, dann frag nach, wir erklären es dir gerne, aber einfach ignorieren funktioniert halt nicht.

**Comment by daj00** [comment]
Yo, ist auch doof gewesen von mir. Danke für die Rückmeldung und ich hoffe, dass ich nicht weiter abgestuft werden muss.

**Comment by Plagiatus** [comment]
Du weißt schon, dass A3 bis Mittwoch im Praktikum verbessert werden muss, wenn du deine Ampel wieder weg haben willst, ja? Also jetzt dann?
