### ISSUE TITLE
Aufgabe 3

### ISSUE THREAD

**Issue by AnnieVoynova** [hs-furtwangen/GIS-SoSe-2020#8]
Ich habe die Beschreibungstext hinzufügt :) Wie kann ich aber der struktur der Container verändern, damit die Fehler mit der 800px Grenze weggehen?

**Comment by Logophoman** [comment]
super 👍  
Ich denke du müsstest einfach so anfangen, dass du deinen gesamten Webseiten-Inhalt erstmal [zentrierst ](https://www.w3schools.com/css/css_align.asp)( z. B. dein Main-Element ) oder indem du alles in der Main in ein Zentriertes DIV packst. Und dadurch werden dann auch alle anderen Elemente zentriert. 

Dann müsstest du natürlich wieder das styling bei manchen Elementen entfernen (also Padding/margin), damit diese Elemente wieder in die Mitte rutschen.

**Comment by Logophoman** [comment]
Du musst das aber auch nicht machen, nur wenn du Lust hast zu üben & besser zu werden kannst du gerne ein wenig rumdoktern 😉 - du hast ja auch keine Ampel bekommen 🚦

**Comment by AnnieVoynova** [comment]
Danke^^ Ich werde es trotzdem verbessern.
